name: CI

on: 
  push:
    branches:
      - main
      - release/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-node@main
      with:
        node-version: '16.x'
    - run: npm ci
    - run: npm run prod
    - uses: w9jds/firebase-action@main
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}